<!-- -->
@extends('master')

@section('content')
<article>
    <h1>Mail</h1>
    <ul>
        <li><a href="http://laravel.com/docs/5.0/mail#configuration">Configuration</a></li>
        <li><a href="http://laravel.com/docs/5.0/mail#basic-usage">Basic Usage</a></li>
        <li><a href="http://laravel.com/docs/5.0/mail#embedding-inline-attachments">Embedding Inline Attachments</a></li>
        <li><a href="http://laravel.com/docs/5.0/mail#queueing-mail">Queueing Mail</a></li>
        <li><a href="http://laravel.com/docs/5.0/mail#mail-and-local-development">Mail &amp; Local Development</a></li>
    </ul>
    <p><a name="configuration"></a></p>
    <h2><a href="http://laravel.com/docs/5.0/mail#configuration">Configuration</a></h2>
    <p>Laravel provides a clean, simple API over the popular <a href="http://swiftmailer.org/">SwiftMailer</a> library. The mail configuration file is <code class=" language-php">config<span class="token operator">/</span>mail<span class="token punctuation">.</span>php</code>, and contains options allowing you to change your SMTP host, port, and credentials, as well as set a global <code class=" language-php">from</code> address for all messages delivered by the library. You may use any SMTP server you wish. If you wish to use the PHP <code class=" language-php">mail</code> function to send mail, you may change the <code class=" language-php">driver</code> to <code class=" language-php">mail</code> in the configuration file. A <code class=" language-php">sendmail</code> driver is also available.</p>
    <h3>API Drivers</h3>
    <p>Laravel also includes drivers for the Mailgun and Mandrill HTTP APIs. These APIs are often simpler and quicker than the SMTP servers. Both of these drivers require that the Guzzle 4 HTTP library be installed into your application. You can add Guzzle 4 to your project by adding the following line to your <code class=" language-php">composer<span class="token punctuation">.</span>json</code> file:</p>
    <pre class=" language-php"><code class=" language-php"><span class="token string">"guzzlehttp/guzzle"</span><span class="token punctuation">:</span> <span class="token string">"~4.0"</span></code></pre>
    <h4>Mailgun Driver</h4>
    <p>To use the Mailgun driver, set the <code class=" language-php">driver</code> option to <code class=" language-php">mailgun</code> in your <code class=" language-php">config<span class="token operator">/</span>mail<span class="token punctuation">.</span>php</code> configuration file. Next, create an <code class=" language-php">config<span class="token operator">/</span>services<span class="token punctuation">.</span>php</code> configuration file if one does not already exist for your project. Verify that it contains the following options:</p>
<pre class=" language-php"><code class=" language-php"><span class="token string">'mailgun'</span> <span class="token operator">=</span><span class="token operator">&gt;</span> <span class="token punctuation">[</span>
        <span class="token string">'domain'</span> <span class="token operator">=</span><span class="token operator">&gt;</span> <span class="token string">'your-mailgun-domain'</span><span class="token punctuation">,</span>
        <span class="token string">'secret'</span> <span class="token operator">=</span><span class="token operator">&gt;</span> <span class="token string">'your-mailgun-key'</span><span class="token punctuation">,</span>
        <span class="token punctuation">]</span><span class="token punctuation">,</span></code></pre>
    <h4>Mandrill Driver</h4>
    <p>To use the Mandrill driver, set the <code class=" language-php">driver</code> option to <code class=" language-php">mandrill</code> in your <code class=" language-php">config<span class="token operator">/</span>mail<span class="token punctuation">.</span>php</code> configuration file. Next, create an <code class=" language-php">config<span class="token operator">/</span>services<span class="token punctuation">.</span>php</code> configuration file if one does not already exist for your project. Verify that it contains the following options:</p>
<pre class=" language-php"><code class=" language-php"><span class="token string">'mandrill'</span> <span class="token operator">=</span><span class="token operator">&gt;</span> <span class="token punctuation">[</span>
        <span class="token string">'secret'</span> <span class="token operator">=</span><span class="token operator">&gt;</span> <span class="token string">'your-mandrill-key'</span><span class="token punctuation">,</span>
        <span class="token punctuation">]</span><span class="token punctuation">,</span></code></pre>
    <h3>Log Driver</h3>
    <p>If the <code class=" language-php">driver</code> option of your <code class=" language-php">config<span class="token operator">/</span>mail<span class="token punctuation">.</span>php</code> configuration file is set to <code class=" language-php">log</code>, all e-mails will be written to your log files, and will not actually be sent to any of the recipients. This is primarily useful for quick, local debugging and content verification.</p>
    <p><a name="basic-usage"></a></p>
    <h2><a href="http://laravel.com/docs/5.0/mail#basic-usage">Basic Usage</a></h2>
    <p>The <code class=" language-php"><span class="token scope">Mail<span class="token punctuation">::</span></span>send</code> method may be used to send an e-mail message:</p>
<pre class=" language-php"><code class=" language-php"><span class="token scope">Mail<span class="token punctuation">::</span></span><span class="token function">send<span class="token punctuation">(</span></span><span class="token string">'emails.welcome'</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token string">'key'</span> <span class="token operator">=</span><span class="token operator">&gt;</span> <span class="token string">'value'</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token keyword">function</span><span class="token punctuation">(</span><span class="token variable">$message</span><span class="token punctuation">)</span>
        <span class="token punctuation">{</span>
        <span class="token variable">$message</span><span class="token operator">-</span><span class="token operator">&gt;</span><span class="token function">to<span class="token punctuation">(</span></span><span class="token string">'foo@example.com'</span><span class="token punctuation">,</span> <span class="token string">'John Smith'</span><span class="token punctuation">)</span><span class="token operator">-</span><span class="token operator">&gt;</span><span class="token function">subject<span class="token punctuation">(</span></span><span class="token string">'Welcome!'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></code></pre>
    <p>The first argument passed to the <code class=" language-php">send</code> method is the name of the view that should be used as the e-mail body. The second is the data to be passed to the view, often as an associative array where the data items are available to the view by <code class=" language-php"><span class="token variable">$key</span></code>. The third is a Closure allowing you to specify various options on the e-mail message.</p>
    <blockquote>
        <p><strong>Note:</strong> A <code class=" language-php"><span class="token variable">$message</span></code> variable is always passed to e-mail views, and allows the inline embedding of attachments. So, it is best to avoid passing a <code class=" language-php">message</code> variable in your view payload.</p>
    </blockquote>
    <p>You may also specify a plain text view to use in addition to an HTML view:</p>
    <pre class=" language-php"><code class=" language-php"><span class="token scope">Mail<span class="token punctuation">::</span></span><span class="token function">send<span class="token punctuation">(</span></span><span class="token punctuation">[</span><span class="token string">'html.view'</span><span class="token punctuation">,</span> <span class="token string">'text.view'</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token variable">$data</span><span class="token punctuation">,</span> <span class="token variable">$callback</span><span class="token punctuation">)</span><span class="token punctuation">;</span></code></pre>
    <p>Or, you may specify only one type of view using the <code class=" language-php">html</code> or <code class=" language-php">text</code> keys:</p>
    <pre class=" language-php"><code class=" language-php"><span class="token scope">Mail<span class="token punctuation">::</span></span><span class="token function">send<span class="token punctuation">(</span></span><span class="token punctuation">[</span><span class="token string">'text'</span> <span class="token operator">=</span><span class="token operator">&gt;</span> <span class="token string">'view'</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token variable">$data</span><span class="token punctuation">,</span> <span class="token variable">$callback</span><span class="token punctuation">)</span><span class="token punctuation">;</span></code></pre>
    <p>You may specify other options on the e-mail message such as any carbon copies or attachments as well:</p>
<pre class=" language-php"><code class=" language-php"><span class="token scope">Mail<span class="token punctuation">::</span></span><span class="token function">send<span class="token punctuation">(</span></span><span class="token string">'emails.welcome'</span><span class="token punctuation">,</span> <span class="token variable">$data</span><span class="token punctuation">,</span> <span class="token keyword">function</span><span class="token punctuation">(</span><span class="token variable">$message</span><span class="token punctuation">)</span>
        <span class="token punctuation">{</span>
        <span class="token variable">$message</span><span class="token operator">-</span><span class="token operator">&gt;</span><span class="token function">from<span class="token punctuation">(</span></span><span class="token string">'us@example.com'</span><span class="token punctuation">,</span> <span class="token string">'Laravel'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

        <span class="token variable">$message</span><span class="token operator">-</span><span class="token operator">&gt;</span><span class="token function">to<span class="token punctuation">(</span></span><span class="token string">'foo@example.com'</span><span class="token punctuation">)</span><span class="token operator">-</span><span class="token operator">&gt;</span><span class="token function">cc<span class="token punctuation">(</span></span><span class="token string">'bar@example.com'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

        <span class="token variable">$message</span><span class="token operator">-</span><span class="token operator">&gt;</span><span class="token function">attach<span class="token punctuation">(</span></span><span class="token variable">$pathToFile</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></code></pre>
    <p>When attaching files to a message, you may also specify a MIME type and / or a display name:</p>
    <pre class=" language-php"><code class=" language-php"><span class="token variable">$message</span><span class="token operator">-</span><span class="token operator">&gt;</span><span class="token function">attach<span class="token punctuation">(</span></span><span class="token variable">$pathToFile</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token string">'as'</span> <span class="token operator">=</span><span class="token operator">&gt;</span> <span class="token variable">$display</span><span class="token punctuation">,</span> <span class="token string">'mime'</span> <span class="token operator">=</span><span class="token operator">&gt;</span> <span class="token variable">$mime</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span></code></pre>
    <p>If you just need to e-mail a simple string instead of an entire view, use the <code class=" language-php">raw</code> method:</p>
<pre class=" language-php"><code class=" language-php"><span class="token scope">Mail<span class="token punctuation">::</span></span><span class="token function">raw<span class="token punctuation">(</span></span><span class="token string">'Text to e-mail'</span><span class="token punctuation">,</span> <span class="token keyword">function</span><span class="token punctuation">(</span><span class="token variable">$message</span><span class="token punctuation">)</span>
        <span class="token punctuation">{</span>
        <span class="token variable">$message</span><span class="token operator">-</span><span class="token operator">&gt;</span><span class="token function">from<span class="token punctuation">(</span></span><span class="token string">'us@example.com'</span><span class="token punctuation">,</span> <span class="token string">'Laravel'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

        <span class="token variable">$message</span><span class="token operator">-</span><span class="token operator">&gt;</span><span class="token function">to<span class="token punctuation">(</span></span><span class="token string">'foo@example.com'</span><span class="token punctuation">)</span><span class="token operator">-</span><span class="token operator">&gt;</span><span class="token function">cc<span class="token punctuation">(</span></span><span class="token string">'bar@example.com'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></code></pre>
    <blockquote>
        <p><strong>Note:</strong> The message instance passed to a <code class=" language-php"><span class="token scope">Mail<span class="token punctuation">::</span></span>send</code> Closure extends the SwiftMailer message class, allowing you to call any method on that class to build your e-mail messages.</p>
    </blockquote>
    <p><a name="embedding-inline-attachments"></a></p>
    <h2><a href="http://laravel.com/docs/5.0/mail#embedding-inline-attachments">Embedding Inline Attachments</a></h2>
    <p>Embedding inline images into your e-mails is typically cumbersome; however, Laravel provides a convenient way to attach images to your e-mails and retrieving the appropriate CID.</p>
    <h4>Embedding An Image In An E-Mail View</h4>
<pre class=" language-php"><code class=" language-php"><span class="token markup"><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>body</span><span class="token punctuation">&gt;</span></span></span>
        Here is an image<span class="token punctuation">:</span>

        <span class="token markup"><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>img</span> <span class="token attr-name">src</span><span class="token attr-value"><span class="token punctuation">=</span><span class="token punctuation">"</span><span class="token php"><span class="token delimiter">&lt;?php</span> <span class="token keyword">echo</span> <span class="token variable">$message</span><span class="token operator">-</span><span class="token operator">&gt;</span><span class="token function">embed<span class="token punctuation">(</span></span><span class="token variable">$pathToFile</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token delimiter">?&gt;</span></span><span class="token punctuation">"</span></span><span class="token punctuation">&gt;</span></span></span>
        <span class="token markup"><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>body</span><span class="token punctuation">&gt;</span></span></span></code></pre>
    <h4>Embedding Raw Data In An E-Mail View</h4>
<pre class=" language-php"><code class=" language-php"><span class="token markup"><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>body</span><span class="token punctuation">&gt;</span></span></span>
        Here is an image from raw data<span class="token punctuation">:</span>

        <span class="token markup"><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>img</span> <span class="token attr-name">src</span><span class="token attr-value"><span class="token punctuation">=</span><span class="token punctuation">"</span><span class="token php"><span class="token delimiter">&lt;?php</span> <span class="token keyword">echo</span> <span class="token variable">$message</span><span class="token operator">-</span><span class="token operator">&gt;</span><span class="token function">embedData<span class="token punctuation">(</span></span><span class="token variable">$data</span><span class="token punctuation">,</span> <span class="token variable">$name</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token delimiter">?&gt;</span></span><span class="token punctuation">"</span></span><span class="token punctuation">&gt;</span></span></span>
        <span class="token markup"><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>body</span><span class="token punctuation">&gt;</span></span></span></code></pre>
    <p>Note that the <code class=" language-php"><span class="token variable">$message</span></code> variable is always passed to e-mail views by the <code class=" language-php">Mail</code> facade.</p>
    <p><a name="queueing-mail"></a></p>
    <h2><a href="http://laravel.com/docs/5.0/mail#queueing-mail">Queueing Mail</a></h2>
    <h4>Queueing A Mail Message</h4>
    <p>Since sending e-mail messages can drastically lengthen the response time of your application, many developers choose to queue e-mail messages for background sending. Laravel makes this easy using its built-in <a href="http://laravel.com/docs/5.0/queues">unified queue API</a>. To queue a mail message, simply use the <code class=" language-php">queue</code> method on the <code class=" language-php">Mail</code> facade:</p>
<pre class=" language-php"><code class=" language-php"><span class="token scope">Mail<span class="token punctuation">::</span></span><span class="token function">queue<span class="token punctuation">(</span></span><span class="token string">'emails.welcome'</span><span class="token punctuation">,</span> <span class="token variable">$data</span><span class="token punctuation">,</span> <span class="token keyword">function</span><span class="token punctuation">(</span><span class="token variable">$message</span><span class="token punctuation">)</span>
        <span class="token punctuation">{</span>
        <span class="token variable">$message</span><span class="token operator">-</span><span class="token operator">&gt;</span><span class="token function">to<span class="token punctuation">(</span></span><span class="token string">'foo@example.com'</span><span class="token punctuation">,</span> <span class="token string">'John Smith'</span><span class="token punctuation">)</span><span class="token operator">-</span><span class="token operator">&gt;</span><span class="token function">subject<span class="token punctuation">(</span></span><span class="token string">'Welcome!'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></code></pre>
    <p>You may also specify the number of seconds you wish to delay the sending of the mail message using the <code class=" language-php">later</code> method:</p>
<pre class=" language-php"><code class=" language-php"><span class="token scope">Mail<span class="token punctuation">::</span></span><span class="token function">later<span class="token punctuation">(</span></span><span class="token number">5</span><span class="token punctuation">,</span> <span class="token string">'emails.welcome'</span><span class="token punctuation">,</span> <span class="token variable">$data</span><span class="token punctuation">,</span> <span class="token keyword">function</span><span class="token punctuation">(</span><span class="token variable">$message</span><span class="token punctuation">)</span>
        <span class="token punctuation">{</span>
        <span class="token variable">$message</span><span class="token operator">-</span><span class="token operator">&gt;</span><span class="token function">to<span class="token punctuation">(</span></span><span class="token string">'foo@example.com'</span><span class="token punctuation">,</span> <span class="token string">'John Smith'</span><span class="token punctuation">)</span><span class="token operator">-</span><span class="token operator">&gt;</span><span class="token function">subject<span class="token punctuation">(</span></span><span class="token string">'Welcome!'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></code></pre>
    <p>If you wish to specify a specific queue or "tube" on which to push the message, you may do so using the <code class=" language-php">queueOn</code> and <code class=" language-php">laterOn</code> methods:</p>
<pre class=" language-php"><code class=" language-php"><span class="token scope">Mail<span class="token punctuation">::</span></span><span class="token function">queueOn<span class="token punctuation">(</span></span><span class="token string">'queue-name'</span><span class="token punctuation">,</span> <span class="token string">'emails.welcome'</span><span class="token punctuation">,</span> <span class="token variable">$data</span><span class="token punctuation">,</span> <span class="token keyword">function</span><span class="token punctuation">(</span><span class="token variable">$message</span><span class="token punctuation">)</span>
        <span class="token punctuation">{</span>
        <span class="token variable">$message</span><span class="token operator">-</span><span class="token operator">&gt;</span><span class="token function">to<span class="token punctuation">(</span></span><span class="token string">'foo@example.com'</span><span class="token punctuation">,</span> <span class="token string">'John Smith'</span><span class="token punctuation">)</span><span class="token operator">-</span><span class="token operator">&gt;</span><span class="token function">subject<span class="token punctuation">(</span></span><span class="token string">'Welcome!'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></code></pre>
    <p><a name="mail-and-local-development"></a></p>
    <h2><a href="http://laravel.com/docs/5.0/mail#mail-and-local-development">Mail &amp; Local Development</a></h2>
    <p>When developing an application that sends e-mail, it's usually desirable to disable the sending of messages from your local or development environment. To do so, you may either call the <code class=" language-php"><span class="token scope">Mail<span class="token punctuation">::</span></span>pretend</code> method, or set the <code class=" language-php">pretend</code> option in the <code class=" language-php">config<span class="token operator">/</span>mail<span class="token punctuation">.</span>php</code> configuration file to <code class=" language-php"><span class="token boolean">true</span></code>. When the mailer is in <code class=" language-php">pretend</code> mode, messages will be written to your application's log files instead of being sent to the recipient.</p>
    <p>If you would like to actually view the test e-mails, consider using a service like <a href="https://mailtrap.io/">MailTrap</a>.</p>
</article>
@stop